### PR TITLE
Added LD_LIBRARY_PATH from inside binary

### PR DESCRIPTION
**Pull request by Mariappan**
Instead of using *.sh to set library path, set it in binary

### CODE REVIEW

**Comment by akiyosi** [comment]
Thank you for PR😃
I think the following variables are not necessary, but do you have any ideas?

```
		_ = os.Setenv("QML_IMPORT_PATH", dir + "qml")
		_ = os.Setenv("QML2_IMPORT_PATH", dir + "qml")
```

**Comment by Mariappan** [comment]
No, I have not digged much on it and just add it from the old gonvim.sh. 
But noticed even without these also, gonvim starts.
So i assume we can safely remove it.

**Comment by Mariappan** [comment]
Again verified. It is not needed, removed it and pushed

**Comment by akiyosi** [comment]
I'm planning to provide static binary on all platforms at 0.4.0. 
Therefore, at some point in the future, this fix code may be deleted again. 
You can generate static binary by referring to the following document.
https://github.com/therecipe/qt/issues/486
https://doc.qt.io/qt-5/linux-deployment.html#building-qt-statically

Or you can use the following docker image `linux_static`.
https://hub.docker.com/r/therecipe/qt/tags

**Comment by Mariappan** [comment]
Oh ok @akiyosi 
Thanks
Does your latest checkin in multigrid branch need some more fixes, it is crashing in my setup ?

**Comment by akiyosi** [comment]
There is no problem with your fix. 
I want to reduce platform specific code as much as possible.

**Pull request merged**
